ClickHouse/clickhouse-js

examples/ping_cloud.ts, src/client.ts
While working on documentation, I noticed a few gaps in examples and typings. More might follow in the following PRs.
=> add "ping" example and typings for method params

__tests__/integration/exec.test.ts, src/client.ts, src/connection/adapter/base_http_adapter.ts, src/connection/adapter/http_search_params.ts, src/connection/connection.ts
This adds an optional `session_id` parameter to each HTTP request.
=> add session support

src/connection/adapter/base_http_adapter.ts
closes https://github.com/ClickHouse/clickhouse-js/issues/123
The PR removes listeners synchronously to avoid a race condition reported in https://github.com/ClickHouse/clickhouse-js/issues/123.
While running https://github.com/ClickHouse/clickhouse-js/blob/main/__tests__/integration/abort_request.test.ts and other test suits, I didn't manage to reproduce the problem described in the old comment, so I removed `setImmediate` workaround.
=> remove request listeners synchronously

.github/workflows/tests.yml, CHANGELOG.md
Adds standard CHANGELOG.md to report notable changes between versions. A separate file is easy to port for the different representations (on the website, application UI, etc.).
Starting from the next release, we can reference CHANGELOG.md from `Release notes` to have a single source of truth.
=> Add Changelog.md

.docker/clickhouse/single_node_tls/Dockerfile, .github/workflows/tests.yml, __tests__/integration/abort_request.test.ts, __tests__/integration/config.test.ts, __tests__/tls/tls.test.ts, docker-compose.cluster.yml, docker-compose.yml
* Update tests to support Node.js 19.x
* Bump CH server version
* Reduce tests flakiness
=> Add Node.js 19.x to the CI pipeline

.build/update_version.ts, .github/workflows/release.yml, CONTRIBUTING.md, __tests__/integration/config.test.ts, __tests__/unit/http_adapter.test.ts, __tests__/unit/user_agent.test.ts, package.json, src/client.ts, src/connection/adapter/base_http_adapter.ts, src/connection/connection.ts, src/utils/process.ts, src/utils/user_agent.ts, src/version.ts, tsconfig.dev.json
Set the User-Agent header according to the [language client spec](https://docs.google.com/document/d/1924Dvy79KXIhfqKpi1EBVY3133pIdoMwgCQtZ-uhEKs/edit#heading=h.ah33hoz5xei2)
=> Set the User-Agent header according to the language client spec

__tests__/integration/fixtures/read_only_user.ts
As of today, read-only user tests started to fail with the Cloud because the password was too simple:
> Invalid password. The password should: contain at least 1 uppercase character, contain at least 1 special character.
=> Fix read-only user tests

.docker/clickhouse/single_node_tls/Dockerfile, CHANGELOG.md, __tests__/unit/encode_values.test.ts, docker-compose.cluster.yml, docker-compose.yml, src/version.ts
Prepare 0.0.14 release with the changeset from #142
=> Prepare 0.0.14, bump CH version to 23.2

src/connection/adapter/base_http_adapter.ts
This somehow related to use of agent and bug in nodejs https://github.com/nodejs/node/issues/47137
Unexpected timeouts on nodejs 19 and nodejs 20 for long running queries (taking more then 3 seconds to execute)
I have reported this issue in https://github.com/ClickHouse/clickhouse-js/issues/149
=> Fix timeout error on nodejs 19/nodejs 20

.github/workflows/tests.yml, __tests__/integration/abort_request.test.ts, __tests__/tls/tls.test.ts
Node.js 14.x EOL.
19.x is EOL soon too, so let's drop it as well.
=> Run tests with Node.js 16/18/20

CHANGELOG.md, __tests__/integration/select_query_binding.test.ts, __tests__/unit/format_query_params.test.ts, src/data_formatter/format_query_params.ts, src/version.ts
The issue was reported some time ago in the community Slack. NULL has to be passed as an actual null symbol (`\N`) instead of a string `'NULL'`. [See a similar fix in clickhouse-connect](https://github.com/ClickHouse/clickhouse-connect/pull/166/files#diff-b324bcc9f3a437c5fd9d073c6d2f04d74a4b598fe631594410f6abe9e0993c04R450).
=> Fix NULL parameters binding

CHANGELOG.md, packages/client-common/__tests__/integration/select_query_binding.test.ts, packages/client-common/__tests__/unit/format_query_params.test.ts, packages/client-common/src/data_formatter/format_query_params.ts
Date objects in query parameters are now serialized as time-zone-agnostic Unix timestamps (NNNNNNNNNN[.NNN], optionally with millisecond-precision) instead of datetime strings without time zones (YYYY-MM-DD HH:MM:SS[.MMM]). This means the server will receive the same absolute timestamp the client sent even if the client's time zone and the database server's time zone differ. Previously, if the server used one time zone and the client used another, Date objects would be encoded in the client's time zone and decoded in the server's time zone and create a mismatch.
For instance, if the server used UTC (GMT) and the client used PST (GMT-8), a Date object for "2023-01-01 13:00:00 **PST**" would be encoded as "2023-01-01 13:00:00.000" and decoded as "2023-01-01 13:00:00 **UTC**" (which is …
=> Serialize Date objects as Unix timestamps to handle different time zones

.docker/clickhouse/single_node_tls/Dockerfile, CHANGELOG.md, docker-compose.cluster.yml, docker-compose.yml, examples/default_format_setting.ts, karma.config.cjs, packages/client-common/__tests__/integration/error_parsing.test.ts, packages/client-common/__tests__/integration/insert.test.ts, packages/client-common/__tests__/integration/select.test.ts, packages/client-common/__tests__/integration/select_query_binding.test.ts, packages/client-common/__tests__/utils/client.ts, packages/client-common/src/error/parse_error.ts, packages/client-common/src/settings.ts, packages/client-common/src/version.ts, packages/client-node/__tests__/integration/node_exec.test.ts, packages/client-node/src/version.ts, packages/client-web/__tests__/integration/web_exec.test.ts, packages/client-web/src/version.ts
This PR adds the missing `default_format` setting and an example of how to use it.
=> Add default_format setting

packages/client-node/src/connection/node_base_connection.ts
In case of an insert call drain the HTTP response instead of destroying it. 
Calling destroy eventually closed the socket even if keep-alive was set. This was a performance limitation.
https://github.com/ClickHouse/clickhouse-js/issues/202
Note: I don't know how to test this
Note: I don't know if it applies to my change
=> Drain insert HTTP response

.build/build_and_prepare.ts, .docker/nginx/local.conf, CHANGELOG.md, CONTRIBUTING.md, package.json, packages/client-common/src/version.ts, packages/client-node/__tests__/integration/node_streaming_e2e.test.ts, packages/client-node/src/result_set.ts, packages/client-node/src/version.ts, packages/client-web/src/version.ts
* Resolves https://github.com/ClickHouse/clickhouse-js/issues/171
* Updates contribution guide
* Prepares 0.2.4
In specific scenarios, with a large number of incoming rows and/or large chunk sizes, incomplete rows were not handled correctly, and produced corrupted UTF-8 strings.
NB: I still need to check the web version, as I suspect it could have the same bug. See #205
=> [Node.js] Fix incomplete rows handling in streaming transformations

CHANGELOG.md, packages/client-common/__tests__/unit/transform_url.test.ts, packages/client-common/src/utils/url.ts, packages/client-common/src/version.ts, packages/client-node/src/connection/node_base_connection.ts, packages/client-node/src/version.ts, packages/client-web/src/connection/web_connection.ts, packages/client-web/src/version.ts
See the [discussion](https://github.com/ClickHouse/clickhouse-js/issues/164#issuecomment-1785166626). Before these changes, `host` such as `http://proxy:8123/clickhouse` will always lose its `/clickhouse` pathname segment after the `transformUrl` call. Now, it is preserved.
=> Don't override `pathname` in `transformUrl`

CHANGELOG.md, examples/insert_cloud.ts, packages/client-common/__tests__/integration/insert.test.ts, packages/client-common/src/version.ts, packages/client-node/src/version.ts, packages/client-web/src/connection/web_connection.ts, packages/client-web/src/version.ts
Add async_insert examples
* Drain insert response stream in Web version - required to properly work with `async_insert`, especially in the Cloudflare Workers context.
* Add Cloud insert examples using `async_insert`
=> Drain insert response stream in Web version

.docker/clickhouse/single_node_tls/Dockerfile, CHANGELOG.md, docker-compose.cluster.yml, docker-compose.yml, karma.config.cjs, packages/client-common/__tests__/integration/data_types.test.ts, packages/client-common/__tests__/integration/insert.test.ts, packages/client-common/src/clickhouse_types.ts, packages/client-common/src/client.ts, packages/client-common/src/connection.ts, packages/client-common/src/index.ts, packages/client-node/__tests__/integration/node_summary.test.ts, packages/client-node/src/connection/node_base_connection.ts
* Adds `summary` field to `insert`/`exec`/`command` result, which is parsed from the `X-ClickHouse-Summary` response header.
* Geo data type test is temporarily marked as ignored as it is still unclear why it fails with a cluster setup on the latest master.
Node.js only. The web version seems to have some CORS limitations.
Question: shall we expose `summary` for `query`, too? It is very unlikely to be correct with streaming scenarios, and for non-streaming ones, we know the number of rows anyway.
Resolves #210
=> Expose `X-ClickHouse-Summary` header info

packages/client-web/__tests__/integration/web_connection.test.ts, packages/client-web/src/client.ts, packages/client-web/src/connection/web_connection.ts
Resolves #186. Related to https://github.com/ClickHouse/clickhouse-js/issues/211#issuecomment-1871032892.
KeepAlive was disabled for the web version without the possibility to re-enable it. 
The changelog and the docs will be updated after #218
=> Make keep_alive configurable in the Web version

packages/client-common/src/client.ts, packages/client-common/src/connection.ts, packages/client-node/__tests__/integration/node_connection.test.ts, packages/client-node/__tests__/unit/node_http_adapter.test.ts, packages/client-node/src/connection/node_base_connection.ts, packages/client-node/src/connection/node_https_connection.ts, packages/client-web/__tests__/integration/web_connection.test.ts, packages/client-web/src/connection/web_connection.ts
This PR enables clickhouse-js to use additional headers in http(s) requests. On my side it was necessary to be able to use a reverse proxy with basic auth in front. For example, something like this is possible from now on.
```ts
createClient({
host: 'https://log.example.com',
username: 'basic_auth_user',
password: 'basic_auth_password',
additionalHeaders: {
'X-ClickHouse-User': 'clickhouse_user',
'X-ClickHouse-Key': 'clickhouse_password',
},
});
```
=> feat: added additional headers to clickhouse requests

packages/client-common/__tests__/integration/data_types.test.ts
Closes https://github.com/ClickHouse/clickhouse-js/issues/89
It looks like the `Nested` data type is already supported, but the documentation says it isn't yet supported: https://clickhouse.com/docs/en/integrations/language-clients/javascript#supported-clickhouse-data-types
https://github.com/ClickHouse/clickhouse-docs/blob/d99f31aa0e8aa50085a737ca3402f09931c75b9f/docs/en/integrations/language-clients/js.md?plain=1#L739
This may lead to confusion.
I'm adding tests to prove that it does work, so I can update the status of support in the docs
=> Add tests for Nested data type

examples/README.md, examples/insert_data_formats_overview.ts, examples/node/insert_file_stream_csv.ts, examples/node/insert_file_stream_ndjson.ts, examples/node/insert_file_stream_parquet.ts, examples/package.json, examples/select_data_formats_overview.ts
More examples: select and insert formats overview. 
I am not sure why we did not have this from the beginning, as these overviews are incredibly useful as a quick reference.
=> More examples: select and insert formats overview

.docker/clickhouse/single_node_tls/Dockerfile, docker-compose.cluster.yml, docker-compose.yml, packages/client-common/__tests__/integration/error_parsing.test.ts, packages/client-node/__tests__/integration/node_streaming_e2e.test.ts
The `UNKNOWN_IDENTIFIER` error message is slightly different now as of 24.3. 
Bumped ClickHouse versions in Docker as well.
=> Update error message assertion in tests

benchmarks/common/handlers.ts, benchmarks/common/index.ts, benchmarks/formats/json.ts, benchmarks/leaks/memory_leak_arrays.ts, benchmarks/leaks/memory_leak_brown.ts, benchmarks/leaks/memory_leak_random_integers.ts, benchmarks/leaks/shared.ts, benchmarks/tsconfig.json, packages/client-common/src/data_formatter/formatter.ts, packages/client-common/src/index.ts, packages/client-node/__tests__/integration/node_query_format_types.test.ts, packages/client-node/src/result_set.ts, packages/client-node/src/utils/stream.ts, packages/client-web/__tests__/integration/web_select_streaming.test.ts, packages/client-web/src/result_set.ts
* Improved performance when decoding the entire set of rows with _streamable_ JSON formats (such as `JSONEachRow` or `JSONCompactEachRow`) by calling the `ResultSet.json()` method. Depending on the dataset, it's between 10-15% (like [cell_towers](https://clickhouse.com/docs/en/getting-started/example-datasets/cell-towers)) and 40% (with large rows and very long strings) less execution time. NB: The actual streaming performance when consuming the `ResultSet.stream()` (which was fast) hasn't changed. Only the `ResultSet.json()` method used a suboptimal stream processing in some instances, and now `ResultSet.json()` just consumes the same stream transformer provided by the `ResultSet.stream()` method.
Before:
```
[1277 ms   ][JSONEachRow       ][SELECT * FROM large_strings ORDER BY id ASC …
```
=> Improved performance when decoding the entire set of rows with streamable JSON formats

CHANGELOG.md, packages/client-common/__tests__/unit/config.test.ts, packages/client-common/src/config.ts, packages/client-common/src/version.ts, packages/client-node/src/version.ts, packages/client-web/src/version.ts
Resolves #258.
Completely overlooked this one (and the unit test for the offending part was entirely wrong).
=> Fix URL configuration with the default HTTP/HTTPS ports

CHANGELOG.md, examples/package.json, packages/client-common/src/client.ts, packages/client-common/src/config.ts, packages/client-common/src/connection.ts, packages/client-common/src/index.ts, packages/client-node/__tests__/unit/node_connection.test.ts, packages/client-node/src/config.ts, packages/client-node/src/connection/node_base_connection.ts, packages/client-web/src/config.ts, packages/client-web/src/connection/web_connection.ts
The `command` method now drains the response stream properly, as the previous implementation could cause the Keep-Alive socket to close after each request.
=> Drain the response stream in the command method

packages/client-common/src/clickhouse_types.ts
The [`rows_before_limit_at_least`](https://clickhouse.com/docs/en/interfaces/formats#json) returned by ClickHouse was missing from the `ResponseJSON<T>` type.
Resolves: #267
=> Add missing property for `ResponseJSON<T>` type

CHANGELOG.md, packages/client-common/__tests__/integration/exec.test.ts, packages/client-common/src/client.ts
Allow overriding `session_id` per query
https://github.com/ClickHouse/clickhouse-js/issues/271
=> Allow override session_id in exec

CHANGELOG.md, jasmine.node.integration.json, packages/client-common/__tests__/integration/exec.test.ts, packages/client-common/__tests__/integration/session.test.ts, packages/client-common/src/client.ts, packages/client-common/src/config.ts
A follow up for #272 
Resolves #271
=> Allow to override session id for a particular request

CHANGELOG.md, packages/client-common/__tests__/integration/totals.test.ts, packages/client-common/src/clickhouse_types.ts, packages/client-node/__tests__/integration/node_errors_parsing.test.ts, packages/client-node/__tests__/integration/node_ping.test.ts, packages/client-web/__tests__/integration/web_error_parsing.test.ts, packages/client-web/__tests__/integration/web_ping.test.ts
Resolves #274
`ResponseJSON<T>.totals` should match `T` instead of the `Record<string, number>` definition.
=> Change incorrect totals TS type

CHANGELOG.md, packages/client-common/src/version.ts, packages/client-node/__tests__/integration/node_custom_http_agent.test.ts, packages/client-node/__tests__/tls/tls.test.ts, packages/client-node/__tests__/unit/node_client.test.ts, packages/client-node/__tests__/unit/node_config.test.ts, packages/client-node/__tests__/unit/node_create_connection.test.ts, packages/client-node/__tests__/utils/http_stubs.ts, packages/client-node/src/config.ts, packages/client-node/src/connection/create_connection.ts, packages/client-node/src/connection/node_base_connection.ts, packages/client-node/src/connection/node_custom_agent_connection.ts, packages/client-node/src/version.ts, packages/client-web/src/version.ts
- Added an option to provide a custom HTTP Agent in the client configuration via the `http_agent` option ([#283](https://github.com/ClickHouse/clickhouse-js/issues/283), related: [#278](https://github.com/ClickHouse/clickhouse-js/issues/278)). The following conditions apply if a custom HTTP Agent is provided:
- The `max_open_connections` and `tls` options will have _no effect_ and will be ignored by the client, as it is a part of the underlying (default) HTTP Agent configuration.
- `keep_alive.enabled` will only regulate the default value of the `Connection` header (`true` -> `Connection: keep-alive`, `false` -> `Connection: close`).
- While the idle socket management will still work, it is now possible to disable it completely by setting the `keep_alive.idle_socket_ttl` value to `0`.
- …
=> Allow to provide a custom http agent and disable the auth header

packages/client-common/src/data_formatter/formatter.ts, packages/client-common/src/index.ts, packages/client-common/src/version.ts, packages/client-node/src/index.ts, packages/client-node/src/version.ts, packages/client-web/src/index.ts, packages/client-web/src/version.ts
Re-export supported formats literals in the Node.js/Web packages for convenience. Previously, only the inferred types were exported.
=> Re-export supported formats literals

CHANGELOG.md, packages/client-common/src/client.ts, packages/client-common/src/connection.ts, packages/client-common/src/index.ts, packages/client-common/src/version.ts, packages/client-node/__tests__/integration/node_exec.test.ts, packages/client-node/src/connection/node_base_connection.ts, packages/client-node/src/connection/stream.ts, packages/client-node/src/index.ts, packages/client-node/src/version.ts, packages/client-web/src/client.ts, packages/client-web/src/version.ts
The `exec` method now accepts an optional `values` parameter, which allows you to pass the request body as a `Stream.Readable`. This can be useful in case of custom insert streaming with arbitrary ClickHouse data formats (which might not be explicitly supported and allowed by the client in the `insert` method yet). 
A very minimal example with CSV (from the tests, it does not make sense as CSV is supported via the normal `insert`, just an illustration):
```ts
const stream = Stream.Readable.from(['42,foobar,"[1,2]"'], {
objectMode: false,
})
const execResult = await client.exec({
query: `INSERT INTO ${tableName} FORMAT CSV`,
values: stream,
})
// the result stream contains nothing useful for an insert 
// and should be immediately drained to release the socket
await …
```
=> An optional `values` parameter in the `exec` method

CHANGELOG.md, packages/client-node/src/index.ts, packages/client-web/src/index.ts
This PR exposes the `NodeClickHouseClient` and `WebClickHouseClient` as values from their respective packages `@clickhouse/client `and `@clickhouse/client-web`. This will allow better integrations with dependency injection frameworks like Nest.js or [tsyringe](https://github.com/microsoft/tsyringe). More details are available on #292.
This PR closes #292.
@maintainers: I added a CHANGELOG entry but I am a bit unsure of the version + the CHANGELOG message. Feel free to change the version number or the message if necessary.
=> Export NodeClickHouseClient and WebClickHouseClient as value

packages/client-common/__tests__/integration/abort_request.test.ts, packages/client-common/src/utils/sleep.ts, packages/client-node/__tests__/integration/node_abort_request.test.ts, packages/client-node/__tests__/integration/node_client.test.ts, packages/client-node/__tests__/unit/node_client.test.ts, packages/client-node/__tests__/unit/node_connection.test.ts, packages/client-node/__tests__/unit/node_connection_compression.test.ts, packages/client-node/__tests__/utils/http_stubs.ts, packages/client-web/__tests__/integration/web_abort_request.test.ts
The way the mocked response message was emitted was not entirely compatible with the changes from #296 (overlooked the pending status of the CI there when merged).
=> Fix main branch tests

examples/insert_ephemeral_columns.ts, packages/client-common/__tests__/integration/data_types.test.ts, packages/client-common/__tests__/integration/insert_specific_columns.test.ts
Remove/rewrite the tests that rely on the old experimental JSON data type since this is failing on the latest CH master. 
The ephemeral columns example is simplified.
=> Adjust the tests that rely on the old `Object('json')` data type

.docker/clickhouse/single_node_tls/Dockerfile, docker-compose.cluster.yml, docker-compose.yml, examples/README.md, examples/dynamic_variant_json.ts, packages/client-common/__tests__/integration/data_types.test.ts
* Bump CH in Docker 24.3 -> 24.8
* Add minimal Variant/Dynamic/JSON examples and tests using the JSONEachRow format.
The website docs will be updated accordingly after this is merged.
=> Add minimal Variant/Dynamic/JSON examples and tests using JSONEachRow format

CHANGELOG.md, docker-compose.yml, packages/client-common/src/clickhouse_types.ts, packages/client-node/__tests__/integration/node_summary.test.ts
* Add optional `real_time_microseconds` to `ClickHouseSummary`
* Fix summary assertions with `head` CH version after https://github.com/ClickHouse/ClickHouse/pull/69032
=> Fix head version tests, add `ClickHouseSummary. real_time_microseconds`

CHANGELOG.md, packages/client-common/src/version.ts, packages/client-node/__tests__/unit/node_result_set.test.ts, packages/client-node/src/result_set.ts, packages/client-node/src/utils/stream.ts, packages/client-node/src/version.ts, packages/client-web/src/version.ts
=> Fix unhandled ResultSet.json errors, prepare 1.6.0

CHANGELOG.md, packages/client-common/__tests__/utils/datasets.ts, packages/client-node/__tests__/integration/node_streaming_e2e.test.ts, packages/client-node/src/connection/node_base_connection.ts, packages/client-web/__tests__/integration/web_select_streaming.test.ts, packages/client-web/src/result_set.ts
Resolves #205 
See also: #171, #204 (there was the same fix, but for Node.js impl only)
=> Fix web impl streaming line breaks with large rows

packages/client-web/src/connection/web_connection.ts
Added missing "crypto" module import so that it won't crash with Deno because of undefined randomUUID function.
Closes #340.
=> Added missing crypto import

packages/client-common/__tests__/integration/read_only_user.test.ts, packages/client-web/__tests__/integration/web_abort_request.test.ts
Adds a cleanup so that it does not create too many dangling read-only users with the Cloud tests. 
Fixes a few flaky web tests.
=> Add read-only users cleanup to the tests

packages/client-web/__tests__/integration/web_abort_request.test.ts
Increase the limit so that the streaming is triggered reliably when the tests are run on a local cluster.
=> Fix a flaky web test

CHANGELOG.md, examples/README.md, examples/role.ts, packages/client-common/__tests__/integration/exec_and_command.test.ts, packages/client-common/__tests__/integration/role.test.ts, packages/client-common/__tests__/unit/to_search_params.test.ts, packages/client-common/__tests__/utils/jasmine.ts, packages/client-common/src/client.ts, packages/client-common/src/config.ts, packages/client-common/src/connection.ts, packages/client-common/src/utils/url.ts, packages/client-node/src/connection/node_base_connection.ts, packages/client-web/src/connection/web_connection.ts
Includes the changeset from #328, minor fixes, and an updated changelog.
=> Role query parameters

CHANGELOG.md, packages/client-common/src/version.ts, packages/client-node/__tests__/tls/tls.test.ts, packages/client-node/src/connection/node_custom_agent_connection.ts, packages/client-node/src/version.ts, packages/client-web/src/version.ts
Closes #352 
Unfortunately, this is a little bit tricky to test.
=> Choose proper HTTP(S) request implementation based on the agent

packages/client-common/__tests__/integration/invalid_string_length.test.ts, packages/client-node/src/utils/stream.ts, packages/client-web/src/utils/stream.ts
Related to https://github.com/ClickHouse/clickhouse-js/issues/106
According to [this commit](https://github.com/v8/v8/commit/ea56bf5513d0cbd2a35a9035c5c2996272b8b728), the client now throws a specific error if the result string length is more than the max allowed string length in V8, which is `2**29 - 24` on a 64-bit platform.
Previously, the exception was too ambiguous: 
- Node.js: `RangeError: Invalid string length`
- Browsers: `InternalError: allocation size overflow`
Now, the error message is supposed to be more clear.
=> Verify the response string length overflow and throw a specific error

packages/client-common/__tests__/integration/select_query_binding.test.ts, packages/client-common/src/client.ts, packages/client-common/src/data_formatter/format_query_params.ts, packages/client-common/src/data_formatter/index.ts, packages/client-common/src/index.ts, packages/client-common/src/utils/url.ts, packages/client-node/src/index.ts, packages/client-web/src/index.ts
Closes #358 
- The client now exports a new wrapper class: `TupleParam`, as tuples need to be serialized as just strings like `('foo','bar')`; however, if it is provided like that in the current version, the single quotes will be escaped, which results in a query failure.
- Added a proper format for the JS `Map` type (it was missing previously), as specifying maps as just objects works only if the CH Map key is a String (cause the JS keys are always strings), and fails in case of Ints, etc.
=> Improvements to the Tuple and Map parameter binding

packages/client-node/__tests__/integration/node_compression.test.ts, packages/client-node/src/connection/compression.ts, packages/client-node/src/connection/node_base_connection.ts
* Fixes #363
* Uses proper logger instance instead of `console.error` to log an error that occurs during the decoding stream
=> Fix an uncaught exception during failure response decompression

CHANGELOG.md, packages/client-common/__tests__/integration/auth.test.ts, packages/client-common/__tests__/unit/config.test.ts, packages/client-common/__tests__/utils/client.ts, packages/client-common/src/config.ts, packages/client-common/src/version.ts, packages/client-node/__tests__/integration/node_jwt_auth.test.ts, packages/client-node/src/version.ts, packages/client-web/__tests__/jwt/web_jwt_auth.test.ts, packages/client-web/src/version.ts
- Keep `username`/`password` on the top level of the config object as it was before #270 
- Move `access_token` to the top level of the config object
- If `access_token` is set alongside `username` or `password`, the client will throw an error.
- Updated the tests and the JS doc
- Updated the changelog 
- Bump the version to 1.10.0
Website docs will be updated shortly after the new release.
=> JWT auth fixes

packages/client-common/src/settings.ts
Related to #370. It is possible to use these settings anyway cause the typings are not very strict; however, it is more convenient to have it there for autocomplete. 
Added some docs entries there as well.
See also https://clickhouse.com/docs/en/interfaces/http#default-database
=> Add `session_timeout` and `session_check` settings typings

packages/client-common/__tests__/integration/select_query_binding.test.ts, packages/client-common/__tests__/unit/format_query_params.test.ts, packages/client-common/src/data_formatter/format_query_params.ts, packages/client-common/src/utils/url.ts
Resolves #374
There was a similar issue with `Array`/`Map` types, too - JS `null` and `undefined` should be printed as the `NULL` keyword instead of `\N` there, as `\N` can be used only for non-nested types, e.g. for something like `Nullable(Int32)`.
See
```
curl "http://localhost:8123?param_tup=%5B'foo',NULL%5D" --data-binary "SELECT {tup: Array(Nullable(String))} t" 
['foo',NULL]
```
```
curl "http://localhost:8123?param_tup=%5B'foo',\N%5D" --data-binary "SELECT {tup: Array(Nullable(String))} t"
Code: 26. DB::Exception: Cannot parse quoted string: expected opening quote ''', got '\': value ['foo',\N] cannot be parsed as Array(Nullable(String)) for query parameter 'tup'. (CANNOT_PARSE_QUOTED_STRING) (version 24.12.2.29 (official build))
```
But
```
curl …
```
=> Fix NULL parameters in Tuples/Maps/Arrays

.github/workflows/tests.yml, package.json, packages/client-node/__tests__/integration/node_jwt_auth.test.ts
Update JWT CI using a different token.
=> Fix JWT CI

packages/client-web/__tests__/integration/web_client.test.ts, packages/client-web/src/config.ts, packages/client-web/src/connection/web_connection.ts
This PR contains the changeset from https://github.com/ClickHouse/clickhouse-js/pull/396, plus a few fixes. Closes #315 
=> Support passing a custom `fetch` function

CHANGELOG.md, package.json, packages/client-common/__tests__/utils/parametrized.ts, packages/client-common/src/client.ts, packages/client-common/src/connection.ts, packages/client-node/__tests__/integration/node_client.test.ts, packages/client-node/__tests__/unit/node_connection.test.ts, packages/client-node/src/connection/node_base_connection.ts, packages/client-node/src/connection/node_https_connection.ts, packages/client-web/__tests__/integration/web_client.test.ts, packages/client-web/src/connection/web_connection.ts, tsconfig.json
Based on #395; allows to override the HTTP headers on the method level for both Node.js and Web implementations. 
Closes #394, as it will be possible to specify the headers as follows:
```ts
const resultSet = await client.query({
http_headers: {
traceparent: '...',
tracestate: '...',
},
)
```
=> Allow to override HTTP headers on the method level

packages/client-node/src/utils/stream.ts
The PR introduces two improvements related to the `stream` utility:
1. Replaces the hardcoded value with the `MAX_STRING_LENGTH` constant from [node.buffer](https://nodejs.org/api/buffer.html#bufferconstantsmax_string_length). The issue with the hardcoded value is that it doesn't account for 32-bit architectures and the function couldn't detect the limit.
2. Replaces the use of `any` with `unknown` in the `isStream` function.
I didn't add tests since the main flow remains unchanged, and the update addresses 32-bit architectures only.
=> Support 32-bit architecture in stream

CHANGELOG.md, packages/client-common/src/config.ts, packages/client-common/src/version.ts, packages/client-node/__tests__/unit/node_client.test.ts, packages/client-node/src/utils/stream.ts, packages/client-node/src/version.ts, packages/client-web/src/version.ts
Includes https://github.com/ClickHouse/clickhouse-js/pull/403
Fixes https://github.com/ClickHouse/clickhouse-js/issues/407
=> Release 1.11.1

.docker/clickhouse/cluster/server1_config.xml, .docker/clickhouse/cluster/server2_config.xml, .docker/clickhouse/single_node/config.xml, .docker/clickhouse/single_node_tls/config.xml
Fixes an occasional CI failure with the current `head` build.
=> Update `os_cpu_busy_time_threshold` to avoid `SERVER_OVERLOADED` error locally

examples/README.md, examples/node/.gitignore, examples/node/insert_arbitrary_format_stream.ts, examples/package.json
Closes #418 - adds an extended example of `exec` usage with `values` from https://github.com/ClickHouse/clickhouse-js/pull/290.
=> Add an arbitrary format insert streaming example using Avro

packages/client-common/src/settings.ts
Added setting  `lightweight_deletes_sync` so that it can be used with JS library.
=> Added setting lightweight_deletes_sync

packages/client-common/src/settings.ts
Adds `allow_experimental_join_condition` to `ClickHouseServerSettings` for better intellisense.
=> chore(types): add missing `allow_experimental_join_condition` to `ClickHouseServerSettings`

.docker/clickhouse/single_node_tls/Dockerfile, docker-compose.cluster.yml, docker-compose.yml, packages/client-common/src/logger.ts, packages/client-node/src/connection/node_base_connection.ts
Closes #439 
Adds a warning like this:
```
[2025-07-15T15:28:53.416Z][ERROR][@clickhouse/client][Connection] Query: socket was closed or ended before the response was fully read. This can potentially result in an uncaught ECONNRESET error! Consider fully consuming, draining, or destroying the response stream 
```
Bump ClickHouse to 25.6
=> Add a warning on a socket closed without fully consuming the stream

examples/README.md, examples/time_time64.ts, packages/client-common/src/settings.ts
Closes #432 
- Adds a JSONEachRow example with the new time types
- Adds a few missing type hints to the settings definition.
=> Add Time/64 examples, update settings typings
